baseURL = "http://example.org/"
languageCode = "en-us"
title = "About me"
theme = "m10c"

[params]
  author = "Muhammad Naeem Akhtar"
  description = "Noob is just a state of mind"
  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/MuhammadNaeemAkhtar"
  [[params.social]]
    icon = "linkedin"
    name = "linkedIn"
    url = "https://linkedin.com/in/muhammad-naeem-akhtar-a40083106/"
